apiVersion: v1
data:
  K8S_STATEFUL_SET_NAME: pingdirectory
  K8S_STATEFUL_SET_SERVICE_NAME: pingdirectory-cluster
  MAKELDIF_USERS: "1000"
  ORCHESTRATION_TYPE: KUBERNETES
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: baseline/pingdirectory
  SERVER_PROFILE_URL: https://github.com/nkreadly07/pingidentity-server-profiles.git
  TAIL_LOG_FILES: '""'
kind: ConfigMap
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory-environment-variables
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdataconsole
  name: pingdataconsole
spec:
  ports:
  - name: https
    port: 8443
  selector:
    role: pingdataconsole
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory
spec:
  ports:
  - name: ldaps
    port: 1636
  - name: https
    port: 1443
  - name: ldap
    port: 1389
  selector:
    role: pingdirectory
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    role: pingdirectory
  name: pingdirectory-cluster
spec:
  clusterIP: None
  ports:
  - name: ldaps
    port: 1636
  publishNotReadyAddresses: true
  selector:
    role: pingdirectory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingdataconsole
  name: pingdataconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingdataconsole
  template:
    metadata:
      labels:
        role: pingdataconsole
      name: pingdataconsole
    spec:
      containers:
      - image: pingidentity/pingdataconsole:edge
        name: pingdataconsole
        ports:
        - containerPort: 8443
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "1"
            memory: 1.5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory
spec:
  replicas: 2
  selector:
    matchLabels:
      role: pingdirectory
  serviceName: pingdirectory-cluster
  template:
    metadata:
      labels:
        role: pingdirectory
      name: pingdirectory
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: pingdirectory-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingdirectory:edge
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /preStop.sh
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/liveness.sh
          failureThreshold: 3
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 5
        name: pingdirectory
        ports:
        - containerPort: 1636
        - containerPort: 1443
        - containerPort: 1389
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/readiness.sh
          failureThreshold: 3
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi
        volumeMounts:
        - mountPath: /opt/out
          name: out-dir
      terminationGracePeriodSeconds: 300
      volumes:
      - name: out-dir
        persistentVolumeClaim:
          claimName: out-dir
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
